In [1]:
import pandas as pd

# Woking with JSON

In [2]:
pd.read_json('./DataSets/train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-21,1761004801,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-21,1761004801,0.0418
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-21,1761004801,0.7580
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-21,1761004801,0.9440
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-21,1761004801,4.3500
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-21,1761004801,1.1600
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-21,1761004801,2.7200
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-21,1761004801,0.1970
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-21,1761004801,0.2580
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-21,1761004801,0.3030

# Working with SQL

In [4]:
# %pip install pymysql

In [5]:
import pymysql

conn = pymysql.connect(
    host='localhost',
    user='root',
    password='root',
    database='sales_database'
)

print("Connected successfully.")

Connected successfully.

In [6]:
df = pd.read_sql_query("Select * from products",conn)

C:\Users\awadh\AppData\Local\Temp\ipykernel_692\760788586.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("Select * from products",conn)

In [7]:
df

,ProductID,ProductName,Category,Price,StockQuantity,Supplier,Rating
0,1,Wireless Mouse,Electronics,25.99,150,Tech Supplies,4.5
1,2,Office Chair,Furniture,120.00,85,Comfort Co,4.7
2,3,Water Bottle,Accessories,15.00,250,AquaGear,4.3
3,4,Laptop Backpack,Accessories,45.99,200,GearUp,4.6
4,5,Gaming Laptop,Electronics,999.99,45,Tech Supplies,4.8
5,6,Desk Lamp,Furniture,35.00,120,LightHouse,4.2
6,7,Bluetooth Speaker,Electronics,59.99,95,SoundWave,4.4
7,8,Standing Desk,Furniture,250.00,50,Comfort Co,4.9
8,9,Fitness Tracker,Electronics,129.99,180,FitTech,4.7
9,10,Coffee Mug,Accessories,9.99,300,MugMasters,4.1